### PR TITLE
Vet Clinic: create animals table

### PR DESCRIPTION
**Pull request by RiyaBulia12**
#### Link => https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_create_tables.md

* Create a database named `vet_clinic`.
* Add `create` query for a table named `animals` in `schema.sql`
* Add `insert` query  to add data  into the `animals` table into the `data.sql`
* Add a screenshot folder with the query result
* Used correct git-flow
* Add License
* Update Readme

### CODE REVIEW

**Review by m05e5 — CHANGES_REQUESTED** [review]
Hi @RiyaBulia12 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have linters configured. please install ruby Linters in your project and ask for another review

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by RiyaBulia12** [comment]
> Hi @RiyaBulia12 ,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that doesn't have linters configured. please install ruby Linters in your project and ask for another review
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

Hi @m05e5,

Thanks for reviewing the project. Linters are not mentioned in the project requirement and that's why I did not add any linters for it. I think the project requirement should be modified to specifically tell the students to add the linters to the project

**Comment by m05e5** [comment]
@RiyaBulia12 ok you're right either they forgot to add linters as a requirement or it's not necessary. Either way, your project is valid and can be reviewed.

**Review by m05e5 — APPROVED** [review]
Hi @RiyaBulia12 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
goodjob

## Highlights
✔️ You're code is clean. well done 

## Optional suggestions


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
